In [1]:
import os
import importlib
import numpy as np
import pandas as pd
import pickle

In [27]:
import Hypers
importlib.reload(Hypers)
import utils
importlib.reload(utils)

<module 'utils' from 'g:\\My Drive\\Chronical\\2024_07\\PNC_Capstone\\utils.py'>

# Test Compustat

In [3]:
records = pd.read_csv(os.path.join(Config.Config.data_path, "WRDS", "07041256.csv"))
records

gvkey    datadate  fyearq  fqtr indfmt consol popsrc datafmt   tic  \
0     3813  2010-01-31    2009     4   INDL      C      D     STD   TGT   
1     3813  2010-04-30    2010     1   INDL      C      D     STD   TGT   
2     3813  2010-07-31    2010     2   INDL      C      D     STD   TGT   
3     3813  2010-10-31    2010     3   INDL      C      D     STD   TGT   
4     3813  2011-01-31    2010     4   INDL      C      D     STD   TGT   
..     ...         ...     ...   ...    ...    ...    ...     ...   ...   
381  64768  2023-03-31    2023     1   INDL      C      D     STD  AMZN   
382  64768  2023-06-30    2023     2   INDL      C      D     STD  AMZN   
383  64768  2023-09-30    2023     3   INDL      C      D     STD  AMZN   
384  64768  2023-12-31    2023     4   INDL      C      D     STD  AMZN   
385  64768  2024-03-31    2024     1   INDL      C      D     STD  AMZN   

               conm  ...      lctq      lltq       ltq      niq    ppentq  \
0       TARGET CORP  ...   11327.0   17859.0   29186.0    936.0   25280.0   
1       TARGET CORP  ...   10197.0   17529.0   27726.0    671.0   25212.0   
2       TARGET CORP  ...   10100.0   18287.0   28387.0    679.0   25401.0   
3       TARGET CORP  ...   11790.0   18280.0   30070.0    535.0   25590.0   
4       TARGET CORP  ...   10070.0   18148.0   28218.0   1035.0   25493.0   
..              ...  ...       ...       ...       ...      ...       ...   
381  AMAZON.COM INC  ...  147570.0  162282.0  309852.0   3172.0  259016.0   
382  AMAZON.COM INC  ...  148238.0  160767.0  309005.0   6750.0  264116.0   
383  AMAZON.COM INC  ...  145214.0  158696.0  303910.0   9879.0  267226.0   
384  AMAZON.COM INC  ...  164917.0  161062.0  325979.0  10624.0  276690.0   
385  AMAZON.COM INC  ...  152965.0  161343.0  314308.0  10431.0  283263.0   

       rectq     revtq      teqq    xsgaq  costat  
0     7882.0   20181.0   15347.0   4041.0       A  
1     6330.0   15593.0   15597.0   3143.0       A  
2     6137.0   15531.0   15268.0   3262.0       A  
3     5955.0   15605.0   14879.0   3344.0       A  
4     7075.0   20661.0   15487.0   3720.0       A  
..       ...       ...       ...      ...     ...  
381  30500.0  127358.0  154526.0  54570.0       A  
382  34900.0  134383.0  168602.0  57183.0       A  
383  38100.0  143083.0  182973.0  56629.0       A  
384  46900.0  169961.0  201875.0  64045.0       A  
385  42200.0  143313.0  216661.0  55145.0       A  

[386 rows x 29 columns]

In [5]:
records.iloc[15, :]

gvkey              3813
datadate     2013-10-31
fyearq             2013
fqtr                  3
indfmt             INDL
consol                C
popsrc                D
datafmt             STD
tic                 TGT
conm        TARGET CORP
curcdq              USD
datacqtr         2013Q3
datafqtr         2013Q3
actq            13153.0
ancq            33220.0
atq             46373.0
cheq              706.0
cogsq           11849.0
invtq           10376.0
lctq            14551.0
lltq            15666.0
ltq             30217.0
niq               341.0
ppentq          31726.0
rectq               NaN
revtq           16925.0
teqq            16156.0
xsgaq            3595.0
costat                A
Name: 15, dtype: object

In [3]:
import CompustatExtractor
importlib.reload(CompustatExtractor)

compustat_extractor = CompustatExtractor.CompustatExtractor()

In [5]:
record_appended = compustat_extractor.append_financial_ratio(records)
record_appended

gvkey    datadate  fyearq  fqtr indfmt consol popsrc datafmt   tic  \
0     3813  2010-01-31    2009     4   INDL      C      D     STD   TGT   
1     3813  2010-04-30    2010     1   INDL      C      D     STD   TGT   
2     3813  2010-07-31    2010     2   INDL      C      D     STD   TGT   
3     3813  2010-10-31    2010     3   INDL      C      D     STD   TGT   
4     3813  2011-01-31    2010     4   INDL      C      D     STD   TGT   
..     ...         ...     ...   ...    ...    ...    ...     ...   ...   
381  64768  2023-03-31    2023     1   INDL      C      D     STD  AMZN   
382  64768  2023-06-30    2023     2   INDL      C      D     STD  AMZN   
383  64768  2023-09-30    2023     3   INDL      C      D     STD  AMZN   
384  64768  2023-12-31    2023     4   INDL      C      D     STD  AMZN   
385  64768  2024-03-31    2024     1   INDL      C      D     STD  AMZN   

               conm  ... costat GrossProfitRatio NetProfitRatio  CurrentRatio  \
0       TARGET CORP  ...      A         0.307170       0.046380      1.626556   
1       TARGET CORP  ...      A         0.314308       0.043032      1.688928   
2       TARGET CORP  ...      A         0.323482       0.043719      1.707426   
3       TARGET CORP  ...      A         0.310413       0.034284      1.556064   
4       TARGET CORP  ...      A         0.292145       0.050094      1.709335   
..              ...  ...    ...              ...            ...           ...   
381  AMAZON.COM INC  ...      A         0.555050       0.024906      0.923094   
382  AMAZON.COM INC  ...      A         0.570005       0.050230      0.947679   
383  AMAZON.COM INC  ...      A         0.560458       0.069044      0.984719   
384  AMAZON.COM INC  ...      A         0.536758       0.062508      1.045077   
385  AMAZON.COM INC  ...      A         0.574714       0.072785      1.072069   

     QuickAcidRatio  CashRatio  EquityMultiplier  ReturnOnAsset  \
0          0.992761   0.194226          2.901740       0.050803   
1          0.978033   0.154751          2.777650       0.038962   
2          0.942277   0.152475          2.859248       0.039374   
3          0.746056   0.079389          3.020969       0.029162   
4          0.955015   0.170010          2.822044       0.060129   
..              ...        ...               ...            ...   
381        0.691543   0.438992          3.005177       0.023286   
382        0.700866   0.435064          2.832748       0.048049   
383        0.740900   0.445095          2.660955       0.069086   
384        0.849063   0.529218          2.614757       0.061642   
385        0.868447   0.559265          2.450690       0.063608   

     ReturnOnEquity  InventoryTurnover  
0          0.060989           1.947625  
1          0.043021           1.474962  
2          0.044472           1.359601  
3          0.035957           1.126806  
4          0.066830           1.925355  
..              ...                ...  
381        0.020527           1.658414  
382        0.040035           1.579359  
383        0.053992           1.776281  
384        0.052627           2.435594  
385        0.048144           1.956818  

[320 rows x 38 columns]

In [15]:
feature_dict = compustat_extractor.get_feature_tensor_dict(record_appended)

In [16]:
feature_dict

OrderedDict([('WMT',
              {2009: {4: tensor([4.8331e+04, 1.2238e+05, 1.7071e+05, 7.9070e+03, 8.3176e+04, 3.3160e+04,
                        5.5561e+04, 4.1909e+04, 9.7470e+04, 4.7580e+03, 1.0231e+05, 1.1362e+05,
                        7.2929e+04, 2.0826e+04, 2.6796e-01, 4.1876e-02, 8.6987e-01, 2.7305e-01,
                        1.4231e-01, 2.3407e+00, 9.8446e-02, 6.5242e-02, 2.5083e+00])},
               2010: {1: tensor([5.1674e+04, 1.2270e+05, 1.7437e+05, 8.5160e+03, 7.2754e+04, 3.5503e+04,
                        6.4512e+04, 4.0932e+04, 1.0544e+05, 3.3010e+03, 1.0293e+05, 9.9811e+04,
                        6.8602e+04, 1.9456e+04, 2.7108e-01, 3.3073e-02, 8.0100e-01, 2.5067e-01,
                        1.3201e-01, 2.5418e+00, 6.3881e-02, 4.8118e-02, 2.0492e+00]),
                2: tensor([5.3045e+04, 1.2390e+05, 1.7694e+05, 1.0195e+04, 7.5554e+04, 3.4793e+04,
                        6.5655e+04, 4.4070e+04, 1.0972e+05, 3.5960e+03, 1.0381e+05, 1.0373e+05,
                 

In [18]:
compustat_extractor.save_pickle(feature_dict, os.path.join(Hypers.Config.data_path, "feature_tensor.pkl"))

In [4]:
load_dict = compustat_extractor.load_pickle(os.path.join(Hypers.Config.data_path, "Retail_07111221.pkl"))

In [6]:
for company in load_dict:
    print(load_dict[company].keys())

dict_keys(['2018Q4', '2019Q4', '2020Q3', '2020Q4', '2021Q1', '2021Q2', '2021Q3', '2021Q4', '2022Q1', '2022Q2', '2022Q3', '2022Q4', '2023Q1', '2023Q2', '2023Q3', '2023Q4', '2024Q1'])
dict_keys(['2009Q4', '2010Q1', '2010Q2', '2010Q3', '2010Q4', '2011Q1', '2011Q2', '2011Q3', '2011Q4', '2012Q1', '2012Q2', '2012Q3', '2012Q4', '2013Q1', '2013Q2', '2013Q3', '2013Q4', '2014Q1', '2014Q2', '2014Q3', '2014Q4', '2015Q1', '2015Q2', '2015Q3', '2015Q4', '2016Q1', '2016Q2', '2016Q3', '2016Q4', '2017Q1', '2017Q2', '2017Q3', '2017Q4', '2018Q1', '2018Q2', '2018Q3', '2018Q4', '2019Q1', '2019Q2', '2019Q3', '2019Q4', '2020Q1', '2020Q2', '2020Q3', '2020Q4', '2021Q1', '2021Q2', '2021Q3', '2021Q4', '2022Q1', '2022Q2', '2022Q3', '2022Q4', '2023Q1', '2023Q2', '2023Q3', '2023Q4', '2024Q1'])
dict_keys(['2010Q2', '2010Q3', '2010Q4', '2011Q1', '2011Q2', '2011Q3', '2011Q4', '2012Q1', '2012Q2', '2012Q3', '2012Q4', '2013Q1', '2013Q2', '2013Q3', '2013Q4', '2014Q1', '2014Q2', '2014Q3', '2014Q4', '2015Q1', '2015Q2', '2015

In [4]:
import utils
importlib.reload(utils)

<module 'utils' from 'g:\\My Drive\\Chronical\\2024_07\\PNC_Capstone\\utils.py'>

In [6]:
merged_dict = utils.load_pickle(os.path.join(Hypers.Config.data_path, "merged_dict.pkl"))
merged_dict

{'ARKO': {'2019Q4': (tensor([ 2.9011e+02,  1.5573e+03,  1.8474e+03,  5.0800e+01,  3.5048e+03,
            1.5775e+02,  3.4048e+02,  1.3120e+03,  1.6525e+03, -4.3539e+01,
            1.3408e+03,  3.6286e+03,  1.9489e+02,  6.9311e+01,  3.4109e-02,
           -1.1999e-02,  8.5206e-01,  3.8874e-01,  1.4920e-01,  9.4790e+00,
           -1.5008e-01, -2.2340e-01,  2.2217e+01]),
   tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])),
  '2020Q4': (tensor([ 6.0941e+02,  2.1304e+03,  2.7398e+03,  3.1142e+02,  1.0195e+03,
            1.6369e+02,  3.8705e+02,  2.1349e+03,  2.4219e+03, -7.9400e+00,
            1.6514e+03,  1.0839e+03,  3.1788e+02,  2.9601e+01,  5.9373e-02,
           -7.3255e-03,  1.5745e+00,  1.1516e+00,  8.0461e-01,  8.6191e+00,
           -1.3029e-02, -2.4978e-02,  6.2286e+00]),
   tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])),
  '2021Q1': (tensor([ 5.3215e+02,  2.1184e+03,  2.6506e+03,  2.2300e+02,  1.1960e+03,
        

In [7]:
for company in merged_dict:
    print(merged_dict[company].keys())

dict_keys(['2019Q4', '2020Q4', '2021Q1', '2021Q2', '2021Q3', '2021Q4', '2022Q1', '2022Q2', '2022Q3', '2022Q4', '2023Q1', '2023Q2', '2023Q3', '2023Q4', '2024Q1'])
dict_keys(['2018Q3', '2018Q4', '2019Q1', '2019Q2', '2019Q3', '2019Q4', '2020Q1', '2020Q2', '2020Q3', '2020Q4', '2021Q1', '2021Q2', '2021Q3', '2021Q4', '2022Q1', '2022Q2', '2022Q3', '2022Q4', '2023Q1', '2023Q2', '2023Q3', '2023Q4', '2024Q1'])
dict_keys(['2010Q4', '2011Q1', '2011Q2', '2011Q3', '2011Q4', '2012Q1', '2012Q2', '2012Q3', '2012Q4', '2013Q1', '2013Q2', '2013Q3', '2013Q4', '2014Q1', '2014Q2', '2014Q3', '2014Q4', '2015Q1', '2015Q2', '2015Q3', '2015Q4', '2016Q1', '2016Q2', '2016Q3', '2016Q4', '2017Q1', '2017Q2', '2017Q3', '2017Q4', '2018Q1', '2018Q2', '2018Q3', '2018Q4', '2019Q1', '2019Q2', '2019Q3', '2019Q4', '2020Q1', '2020Q2', '2020Q3', '2020Q4', '2021Q1', '2021Q2', '2021Q3', '2021Q4', '2022Q1', '2022Q2', '2022Q3', '2022Q4', '2023Q1', '2023Q2', '2023Q3', '2023Q4', '2024Q1'])
dict_keys(['2021Q3', '2021Q4', '2022Q1', '20

: 

# Custom Dataset

In [21]:
import RatingSet
importlib.reload(RatingSet)

<module 'RatingSet' from 'g:\\My Drive\\Chronical\\2024_07\\PNC_Capstone\\RatingSet.py'>

In [22]:
merged_dict = utils.load_pickle(os.path.join(Hypers.Config.data_path, "merged_dict.pkl"))
for comapny_name, record in merged_dict.items():
    for period, (feature, label) in record.items():
        print(feature.shape, label.shape)
        print(feature, label)
        break
    break

torch.Size([23]) torch.Size([1])
tensor([ 2.9011e+02,  1.5573e+03,  1.8474e+03,  5.0800e+01,  3.5048e+03,
         1.5775e+02,  3.4048e+02,  1.3120e+03,  1.6525e+03, -4.3539e+01,
         1.3408e+03,  3.6286e+03,  1.9489e+02,  6.9311e+01,  3.4109e-02,
        -1.1999e-02,  8.5206e-01,  3.8874e-01,  1.4920e-01,  9.4790e+00,
        -1.5008e-01, -2.2340e-01,  2.2217e+01]) tensor([10.])


In [23]:
rating_set = RatingSet.RatingSet(merged_dict)
print(len(rating_set))
print(rating_set[0][0].shape, rating_set[0][1].shape)
print(rating_set[0][0], rating_set[0][1])

10
torch.Size([15, 23]) torch.Size([15, 1])
tensor([[ 2.9011e+02,  1.5573e+03,  1.8474e+03,  5.0800e+01,  3.5048e+03,
          1.5775e+02,  3.4048e+02,  1.3120e+03,  1.6525e+03, -4.3539e+01,
          1.3408e+03,  3.6286e+03,  1.9489e+02,  6.9311e+01,  3.4109e-02,
         -1.1999e-02,  8.5206e-01,  3.8874e-01,  1.4920e-01,  9.4790e+00,
         -1.5008e-01, -2.2340e-01,  2.2217e+01],
        [ 6.0941e+02,  2.1304e+03,  2.7398e+03,  3.1142e+02,  1.0195e+03,
          1.6369e+02,  3.8705e+02,  2.1349e+03,  2.4219e+03, -7.9400e+00,
          1.6514e+03,  1.0839e+03,  3.1788e+02,  2.9601e+01,  5.9373e-02,
         -7.3255e-03,  1.5745e+00,  1.1516e+00,  8.0461e-01,  8.6191e+00,
         -1.3029e-02, -2.4978e-02,  6.2286e+00],
        [ 5.3215e+02,  2.1184e+03,  2.6506e+03,  2.2300e+02,  1.1960e+03,
          1.7112e+02,  3.6761e+02,  2.1036e+03,  2.3712e+03, -1.4736e+01,
          1.6447e+03,  1.2619e+03,  2.7932e+02,  2.6713e+01,  5.2198e-02,
         -1.1678e-02,  1.4476e+00,  9.8208e-

In [24]:
from torch.utils.data import DataLoader

In [28]:
rating_loader = DataLoader(rating_set, batch_size=2, shuffle=True, collate_fn=utils.custom_collate_fn)

In [29]:
for feature_b, label_b, mask in rating_loader:
    print(feature_b.shape, label_b.shape, mask.shape)
    print(feature_b)
    print(label_b)
    print(mask)
    break

torch.Size([2, 15, 23]) torch.Size([2, 15]) torch.Size([2, 15])
tensor([[[ 2.9011e+02,  1.5573e+03,  1.8474e+03,  5.0800e+01,  3.5048e+03,
           1.5775e+02,  3.4048e+02,  1.3120e+03,  1.6525e+03, -4.3539e+01,
           1.3408e+03,  3.6286e+03,  1.9489e+02,  6.9311e+01,  3.4109e-02,
          -1.1999e-02,  8.5206e-01,  3.8874e-01,  1.4920e-01,  9.4790e+00,
          -1.5008e-01, -2.2340e-01,  2.2217e+01],
         [ 6.0941e+02,  2.1304e+03,  2.7398e+03,  3.1142e+02,  1.0195e+03,
           1.6369e+02,  3.8705e+02,  2.1349e+03,  2.4219e+03, -7.9400e+00,
           1.6514e+03,  1.0839e+03,  3.1788e+02,  2.9601e+01,  5.9373e-02,
          -7.3255e-03,  1.5745e+00,  1.1516e+00,  8.0461e-01,  8.6191e+00,
          -1.3029e-02, -2.4978e-02,  6.2286e+00],
         [ 5.3215e+02,  2.1184e+03,  2.6506e+03,  2.2300e+02,  1.1960e+03,
           1.7112e+02,  3.6761e+02,  2.1036e+03,  2.3712e+03, -1.4736e+01,
           1.6447e+03,  1.2619e+03,  2.7932e+02,  2.6713e+01,  5.2198e-02,
          -